# Generated by Django 6.0.3 on 2026-04-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=20, unique=True)),
                ('url_stream', models.CharField(max_length=255)),
                ('setor', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('alerta', 'Alerta')], default='offline', max_length=10)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['identificador'],
            },
        ),
    ]
