# Generated by Django 6.0.3 on 2026-05-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_epi', models.CharField(choices=[('helmet', 'Capacete'), ('gloves', 'Luvas'), ('goggles', 'Oculos de Protecao'), ('vest', 'Colete Refletivo'), ('shoes', 'Botina de Seguranca'), ('mask', 'Mascara')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_epi', to='cameras.camera')),
            ],
            options={
                'ordering': ['camera', 'tipo_epi'],
                'unique_together': {('camera', 'tipo_epi')},
            },
        ),
    ]
