# Generated by Django 6.0.3 on 2026-04-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('epi_ausente', 'EPI Ausente'), ('equipment_fault', 'Falha de Equipamento'), ('conformidade', 'Conformidade')], max_length=20)),
                ('status', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Nao Conforme')], default='nao_conforme', max_length=15)),
                ('epis_ausentes', models.JSONField(default=list)),
                ('frame_path', models.CharField(blank=True, max_length=255)),
                ('pessoas_detectadas', models.IntegerField(default=0)),
                ('confianca', models.FloatField(default=0.0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='cameras.camera')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
