# Generated by Django 6.0.3 on 2026-05-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('deteccao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('critico', 'Critico'), ('aviso', 'Aviso'), ('info', 'Info')], default='aviso', max_length=10)),
                ('mensagem', models.TextField()),
                ('reconhecido', models.BooleanField(default=False)),
                ('reconhecido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cameras.camera')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='deteccao.ocorrencia')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
